name: Greetings

on:
  fork:
    push:
      branches: [main]
    issues:
      types: [opened]
    pull_request_target:
      types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Welcome Action
        uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Congratulations, @${{ github.actor }}! 🎉 Thank you for creating your issue...'
          pr-message: 'Great job, @${{ github.actor }}! 🎉 Thank you for submitting your first pull request...'
          footer: 'We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember...'

